export const actions = {
  GET_UPDATES: "GET_UPDATES",
  GET_UPDATES_SUCCESS: "GET_UPDATES_SUCCESS",
  GET_UPDATES_FAILURE: "GET_UPDATES_FAILURE",

  ADD_UPDATE: "ADD_UPDATE",
  ADD_UPDATE_SUCCESS: "ADD_UPDATE_SUCCESS",
  ADD_UPDATE_FAILURE: "ADD_UPDATE_FAILURE",

  DELETE_UPDATE: "DELETE_UPDATE",
  DELETE_UPDATE_SUCCESS: "DELETE_UPDATE_SUCCESS",
  DELETE_UPDATE_FAILURE: "DELETE_UPDATE_FAILURE",

  GET_DIAGNOSTICS: "GET_DIAGNOSTICS",
  GET_DIAGNOSTICS_SUCCESS: "GET_DIAGNOSTICS_SUCCESS",
  GET_DIAGNOSTICS_FAILURE: "GET_DIAGNOSTICS_FAILURE",
};

export default actions;
