export const actions = {
  ADD_UPDATE: "ADD_UPDATE",
  ADD_UPDATE_SUCCESS: "ADD_UPDATE_SUCCESS",
  ADD_UPDATE_FAILURE: "ADD_UPDATE_FAILURE",

  GET_UPDATES: "GET_UPDATES",
  GET_UPDATES_SUCCESS: "GET_UPDATES_SUCCESS",
  GET_UPDATES_FAILURE: "GET_UPDATES_FAILURE",
};

export default actions;
