import { Delete } from "lucide-react";

export const actions = {
  GET_CONTACTS: "GET_CONTACTS",
  GET_CONTACTS_SUCCESS: "GET_CONTACTS_SUCCESS",
  GET_CONTACTS_FAILURE: "GET_CONTACTS_FAILURE",

  ADD_CONTACT: "ADD_CONTACT",
  ADD_CONTACT_SUCCESS: "ADD_CONTACT_SUCCESS",
  ADD_CONTACT_FAILURE: "ADD_CONTACT_FAILURE",

  EDIT_CONTACT: "EDIT_CONTACT",
  EDIT_CONTACT_SUCCESS: "EDIT_CONTACT_SUCCESS",
  EDIT_CONTACT_FAILURE: "EDIT_CONTACT_FAILURE",

  DELETE_CONTACT: "DELETE_CONTACT",
  DELETE_CONTACT_SUCCESS: "DELETE_CONTACT_SUCCESS",
  DELETE_CONTACT_FAILURE: "DELETE_CONTACT_FAILURE",

  GET_SESSION: "GET_SESSION",
  GET_SESSION_SUCCESS: "GET_SESSION_SUCCESS",
  GET_SESSION_FAILURE: "GET_SESSION_FAILURE",
};

export default actions;
